package store

import (
	"context"
	"strings"
	"time"
)

// This file is DB Phase 5's PostgreSQL schema/migration counterpart to
// migrate() in store.go. It intentionally does not try to replay SQLite's
// migrate() history of incremental "CREATE TABLE IF NOT EXISTS" plus
// tolerant "ALTER TABLE ADD COLUMN" statements - PostgreSQL only exists as
// a supported runtime target starting with this phase, so there is no
// pre-existing PostgreSQL installation whose older schema needs upgrading
// (unlike SQLite, which has real installs going back to before several of
// those columns existed). postgresSchemaDDL instead states the single,
// current, cumulative schema directly - the same end state SQLite's
// migrate() reaches after every ALTER TABLE runs - which is what DB Phase
// 5's "empty PostgreSQL -> latest schema" test scenario calls for. Should
// a later phase need to evolve the PostgreSQL schema further, add
// incremental ALTER TABLE statements here the same way SQLite's migrate()
// does; this baseline does not need to be (and should not be) rewritten
// to simulate history that never happened for PostgreSQL.
//
// Column types intentionally differ from a "native" PostgreSQL schema in
// two ways, both to keep every query string in this package (store.go)
// engine-agnostic rather than needing a second, parallel set of queries:
//
//  1. Every boolean-shaped column (enabled, notify, released, is_local,
//     ...) is a plain INTEGER storing 0/1, exactly like SQLite, rather
//     than PostgreSQL's native BOOLEAN. This keeps every literal
//     comparison already in store.go's query strings ("WHERE
//     download=1", "SET is_local=?", ...) valid unmodified on both
//     engines; postgres_rewrite.go's convertBoolArgs converts a Go bool
//     argument to 0/1 at the driver layer for exactly this reason, and
//     scanning an INTEGER 0/1 back into a Go bool works natively on both
//     engines without help. See that file's doc comment for the full
//     rationale and the empirical check (a Go bool cannot be bound
//     directly against a PostgreSQL INTEGER column - pgx rejects it -
//     which is why this conversion exists at all).
//  2. Autoincrementing primary keys use PostgreSQL's identity-column
//     syntax (GENERATED BY DEFAULT AS IDENTITY) rather than SQLite's
//     INTEGER PRIMARY KEY rowid aliasing - the two are not textually
//     compatible, but Dialect.InsertReturningID (dialect.go) already
//     abstracts the one place that distinction is visible to callers
//     (PostgreSQL needs INSERT...RETURNING id instead of
//     Result.LastInsertId()), so no other change is needed. Only the 9
//     tables actually relying on an application-assigned/generated id
//     (sites, releases, filter_presets, job_history, downloads,
//     path_mappings, pipeline_steps, pipeline_logs, notifications) use
//     it; tables with a fixed, foreign-key-derived, or composite primary
//     key (users, user_preferences, sessions, settings, watchlist_sync,
//     release_actresses, release_tags, release_sites, pipeline_runs) do
//     not.
//
// DATETIME (SQLite's storage class for time.Time - modernc.org/sqlite
// marshals it as text) becomes TIMESTAMPTZ, PostgreSQL's standard type
// for representing an instant - every timestamp this package writes is
// already time.Now().UTC(), so this is a direct, lossless mapping.
//
// CREATE TABLE/INDEX use IF NOT EXISTS throughout, exactly like SQLite's
// migrate(), so this function is safe to call unconditionally on every
// startup, matching the pattern that function already established -
// PostgreSQL has supported CREATE INDEX IF NOT EXISTS since 9.5 and ADD
// COLUMN IF NOT EXISTS since 9.6, both long predating the PostgreSQL 18
// baseline DB Phase 1A targets.
const postgresSchemaDDL = `
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS sites (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title TEXT NOT NULL UNIQUE,
	type TEXT NOT NULL DEFAULT 'Site',
	name TEXT NOT NULL,
	url TEXT NOT NULL DEFAULT '',
	notify INTEGER NOT NULL DEFAULT 0,
	enabled INTEGER NOT NULL DEFAULT 1,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	download INTEGER NOT NULL DEFAULT 0,
	download_mode TEXT NOT NULL DEFAULT '',
	auto_monitor_future INTEGER NOT NULL DEFAULT 0,
	watchlist INTEGER NOT NULL DEFAULT 0,
	rss_url TEXT NOT NULL DEFAULT '',
	last_scraped_at TIMESTAMPTZ,
	last_scrape_pages INTEGER NOT NULL DEFAULT 0,
	last_scrape_added INTEGER NOT NULL DEFAULT 0,
	last_scrape_updated INTEGER NOT NULL DEFAULT 0,
	last_scrape_state TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_sites_title_trgm ON sites USING gin(title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_sites_title_filter_trgm ON sites USING gin(LOWER(title) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS releases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
	video_id TEXT NOT NULL,
	scraper_id TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL,
	release_date TEXT NOT NULL DEFAULT '',
	source TEXT NOT NULL,
	image_url TEXT NOT NULL DEFAULT '',
	product_url TEXT NOT NULL DEFAULT '',
	director TEXT NOT NULL DEFAULT '',
	studio TEXT NOT NULL DEFAULT '',
	label TEXT NOT NULL DEFAULT '',
	duration TEXT NOT NULL DEFAULT '',
	story TEXT NOT NULL DEFAULT '',
	screenshots TEXT NOT NULL DEFAULT '[]',
	screenshots_checked_at TIMESTAMPTZ,
	released INTEGER NOT NULL DEFAULT 0,
	is_local INTEGER NOT NULL DEFAULT 0,
	notified INTEGER NOT NULL DEFAULT 0,
	notify_on_release INTEGER NOT NULL DEFAULT 0,
	watchlist INTEGER NOT NULL DEFAULT 0,
	watchlist_at TIMESTAMPTZ,
	monitor_download INTEGER NOT NULL DEFAULT 0,
	site_monitor_download INTEGER NOT NULL DEFAULT 0,
	monitor_reason TEXT NOT NULL DEFAULT '',
	monitor_site_id BIGINT NOT NULL DEFAULT 0,
	identity_key TEXT NOT NULL DEFAULT '',
	stash_scene_id TEXT NOT NULL DEFAULT '',
	stash_added_at TIMESTAMPTZ,
	stash_created_at TIMESTAMPTZ,
	stash_release_date TEXT NOT NULL DEFAULT '',
	allow_non_preferred_filenames INTEGER NOT NULL DEFAULT 0,
	ignore_local_force_download INTEGER NOT NULL DEFAULT 0,
	o_counter INTEGER NOT NULL DEFAULT 0,
	play_count INTEGER NOT NULL DEFAULT 0,
	last_played_at TEXT NOT NULL DEFAULT '',
	last_o_count_at TEXT NOT NULL DEFAULT '',
	is_preferred INTEGER NOT NULL DEFAULT 1,
	added_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	UNIQUE(site_id, video_id)
);
CREATE INDEX IF NOT EXISTS idx_releases_date ON releases(release_date);
CREATE INDEX IF NOT EXISTS idx_releases_added ON releases(added_at);
CREATE INDEX IF NOT EXISTS idx_releases_site ON releases(site_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_releases_identity ON releases(identity_key) WHERE identity_key<>'';
CREATE INDEX IF NOT EXISTS idx_releases_released_date ON releases(released,release_date DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_releases_updated ON releases(updated_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_releases_title_order ON releases(LOWER(title),id);
CREATE INDEX IF NOT EXISTS idx_releases_studio_order ON releases(LOWER(studio),id);
CREATE INDEX IF NOT EXISTS idx_releases_label_order ON releases(LOWER(label),id);
CREATE INDEX IF NOT EXISTS idx_releases_video_id_trgm ON releases USING gin(video_id gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_title_trgm ON releases USING gin(title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_studio_trgm ON releases USING gin(studio gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_label_trgm ON releases USING gin(label gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_studio_filter_trgm ON releases USING gin(LOWER(studio) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_label_filter_trgm ON releases USING gin(LOWER(label) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_story_trgm ON releases USING gin(story gin_trgm_ops);

CREATE TABLE IF NOT EXISTS settings (
	key TEXT PRIMARY KEY,
	value TEXT NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY CHECK(id=1),
	username TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
	token TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	expires_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS user_preferences (
	user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	state TEXT NOT NULL DEFAULT '{}',
	updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS filter_presets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL DEFAULT 1 REFERENCES users(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	state TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS job_history (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kind TEXT NOT NULL,
	state TEXT NOT NULL,
	mode TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	scheduled INTEGER NOT NULL DEFAULT 0,
	site_count INTEGER NOT NULL DEFAULT 0,
	site_title TEXT NOT NULL DEFAULT '',
	provider TEXT NOT NULL DEFAULT '',
	started_at TIMESTAMPTZ,
	finished_at TIMESTAMPTZ,
	added INTEGER NOT NULL DEFAULT 0,
	updated INTEGER NOT NULL DEFAULT 0,
	skipped INTEGER NOT NULL DEFAULT 0,
	error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS download_search_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	schedule TEXT NOT NULL,
	started_at TIMESTAMPTZ NOT NULL,
	finished_at TIMESTAMPTZ NOT NULL,
	checked INTEGER NOT NULL DEFAULT 0,
	found INTEGER NOT NULL DEFAULT 0,
	downloaded INTEGER NOT NULL DEFAULT 0,
	skipped INTEGER NOT NULL DEFAULT 0,
	failed INTEGER NOT NULL DEFAULT 0,
	error TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_download_search_runs_schedule_finished ON download_search_runs(schedule,finished_at DESC);

CREATE TABLE IF NOT EXISTS downloads (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	release_id BIGINT REFERENCES releases(id) ON DELETE SET NULL,
	provider TEXT NOT NULL DEFAULT '',
	source_type TEXT NOT NULL DEFAULT '',
	source_reference TEXT NOT NULL DEFAULT '',
	query TEXT NOT NULL DEFAULT '',
	torrent_hash TEXT NOT NULL DEFAULT '',
	name TEXT NOT NULL DEFAULT '',
	files TEXT NOT NULL DEFAULT '[]',
	status TEXT NOT NULL,
	match_reason TEXT NOT NULL DEFAULT '',
	qb_response TEXT NOT NULL DEFAULT '',
	post_status TEXT NOT NULL DEFAULT '',
	error TEXT NOT NULL DEFAULT '',
	seed_ratio REAL NOT NULL DEFAULT 0,
	progress REAL NOT NULL DEFAULT 0,
	seeds INTEGER NOT NULL DEFAULT 0,
	peers INTEGER NOT NULL DEFAULT 0,
	eta_seconds INTEGER NOT NULL DEFAULT 0,
	seen_complete BIGINT NOT NULL DEFAULT 0,
	filename_pattern_excluded INTEGER NOT NULL DEFAULT 0,
	added_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_downloads_status ON downloads(status);
CREATE INDEX IF NOT EXISTS idx_downloads_release ON downloads(release_id);
CREATE INDEX IF NOT EXISTS idx_downloads_release_status_updated ON downloads(release_id,status,updated_at DESC);

CREATE TABLE IF NOT EXISTS path_mappings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	download_prefix TEXT NOT NULL UNIQUE,
	local_prefix TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pipeline_steps (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	position INTEGER NOT NULL,
	trigger TEXT NOT NULL DEFAULT 'download_completed',
	type TEXT NOT NULL,
	name TEXT NOT NULL,
	config TEXT NOT NULL DEFAULT '{}',
	enabled INTEGER NOT NULL DEFAULT 1,
	timeout_seconds INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pipeline_logs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	download_id BIGINT NOT NULL REFERENCES downloads(id) ON DELETE CASCADE,
	step_id BIGINT REFERENCES pipeline_steps(id) ON DELETE SET NULL,
	state TEXT NOT NULL,
	configuration TEXT NOT NULL DEFAULT '{}',
	output TEXT NOT NULL DEFAULT '',
	error TEXT NOT NULL DEFAULT '',
	started_at TIMESTAMPTZ NOT NULL,
	finished_at TIMESTAMPTZ
);
-- Added directly to the baseline (DB Phase 6's cross-reference/index
-- audit): pipeline_logs.download_id is a frequently queried foreign key
-- (PipelineLogs(ctx, downloadID)) with no backing index in the prior
-- schema on either engine - PostgreSQL, like SQLite, never creates one
-- automatically for a foreign key. Added here for PostgreSQL and to
-- store.go's migrate() for SQLite so the two engines stay in sync.
CREATE INDEX IF NOT EXISTS idx_pipeline_logs_download ON pipeline_logs(download_id);

CREATE TABLE IF NOT EXISTS notifications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	release_id BIGINT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
	type TEXT NOT NULL,
	message TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL,
	UNIQUE(release_id, type)
);
CREATE INDEX IF NOT EXISTS idx_notifications_release_created ON notifications(release_id,created_at DESC);

CREATE TABLE IF NOT EXISTS watchlist_sync (
	release_id BIGINT PRIMARY KEY REFERENCES releases(id) ON DELETE CASCADE,
	stash_scene_id TEXT NOT NULL,
	tag_id TEXT NOT NULL,
	synced_at TIMESTAMPTZ NOT NULL,
	result TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS historical_backfill_state (
	id INTEGER PRIMARY KEY CHECK(id=1), state TEXT NOT NULL DEFAULT 'idle', updated_at TIMESTAMPTZ NOT NULL
);
INSERT INTO historical_backfill_state(id,state,updated_at) VALUES(1,'idle',CURRENT_TIMESTAMP) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS historical_backfill_sources (
	url TEXT PRIMARY KEY, kind TEXT NOT NULL, name TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'pending',
	cursor_date TEXT NOT NULL DEFAULT '', resume_date TEXT NOT NULL DEFAULT '', next_page INTEGER NOT NULL DEFAULT 1,
	page_limit INTEGER NOT NULL DEFAULT 0, pages_completed INTEGER NOT NULL DEFAULT 0, catchup_only INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS historical_backfill_items (
	video_id TEXT PRIMARY KEY, release_date TEXT NOT NULL DEFAULT '', state TEXT NOT NULL,
	source_url TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_historical_backfill_items_state ON historical_backfill_items(state);

CREATE TABLE IF NOT EXISTS release_actresses (
	release_id BIGINT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
	position INTEGER NOT NULL,
	name TEXT NOT NULL,
	name_normalized TEXT NOT NULL,
	PRIMARY KEY(release_id, name_normalized)
);
CREATE INDEX IF NOT EXISTS idx_release_actresses_name ON release_actresses(name_normalized, release_id);
CREATE INDEX IF NOT EXISTS idx_release_actresses_release_position ON release_actresses(release_id, position);
CREATE INDEX IF NOT EXISTS idx_release_actresses_name_trgm ON release_actresses USING gin(name_normalized gin_trgm_ops);

CREATE TABLE IF NOT EXISTS release_tags (
	release_id BIGINT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
	position INTEGER NOT NULL,
	name TEXT NOT NULL,
	name_normalized TEXT NOT NULL,
	PRIMARY KEY(release_id, name_normalized)
);
CREATE INDEX IF NOT EXISTS idx_release_tags_name ON release_tags(name_normalized, release_id);
CREATE INDEX IF NOT EXISTS idx_release_tags_release_position ON release_tags(release_id, position);
CREATE INDEX IF NOT EXISTS idx_release_tags_name_trgm ON release_tags USING gin(name_normalized gin_trgm_ops);

CREATE TABLE IF NOT EXISTS release_sites (
	release_id BIGINT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
	site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
	site_monitor_download INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(release_id, site_id)
);
CREATE INDEX IF NOT EXISTS idx_release_sites_site ON release_sites(site_id, release_id);

CREATE TABLE IF NOT EXISTS pipeline_runs (
	download_id BIGINT NOT NULL REFERENCES downloads(id) ON DELETE CASCADE,
	trigger TEXT NOT NULL,
	state TEXT NOT NULL,
	error TEXT NOT NULL DEFAULT '',
	started_at TIMESTAMPTZ NOT NULL,
	finished_at TIMESTAMPTZ,
	PRIMARY KEY(download_id, trigger)
);

-- TODO-2.0 Phase 2 "Missing Library Files": see the matching CREATE TABLE
-- in store.go's migrate() for the full column-by-column rationale. id uses
-- the same BIGINT GENERATED BY DEFAULT AS IDENTITY convention as the other
-- application-assigned-id tables in this file (see the doc comment above);
-- release_id is a plain BIGINT rather than a foreign key because 0 (no
-- release matched/retrieved yet) is a valid, common value this column
-- holds, and ON DELETE behavior for "the linked release was deleted" is
-- deliberately "leave the missing-scene row and let the next scan/action
-- re-resolve it" rather than a cascading delete or a hard constraint
-- violation.
CREATE TABLE IF NOT EXISTS stash_missing_scenes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stash_scene_id TEXT NOT NULL UNIQUE,
	title TEXT NOT NULL DEFAULT '',
	code TEXT NOT NULL DEFAULT '',
	date TEXT NOT NULL DEFAULT '',
	path TEXT NOT NULL DEFAULT '',
	paths TEXT NOT NULL DEFAULT '[]',
	o_counter INTEGER NOT NULL DEFAULT 0,
	play_count INTEGER NOT NULL DEFAULT 0,
	last_played_at TEXT NOT NULL DEFAULT '',
	studio TEXT NOT NULL DEFAULT '',
	tags TEXT NOT NULL DEFAULT '[]',
	urls TEXT NOT NULL DEFAULT '[]',
	javlibrary_url TEXT NOT NULL DEFAULT '',
	release_id BIGINT NOT NULL DEFAULT 0,
	status TEXT NOT NULL DEFAULT 'missing',
	message TEXT NOT NULL DEFAULT '',
	first_seen_at TIMESTAMPTZ NOT NULL,
	last_scan_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stash_missing_release ON stash_missing_scenes(release_id);
CREATE INDEX IF NOT EXISTS idx_stash_missing_status ON stash_missing_scenes(status);
CREATE INDEX IF NOT EXISTS idx_stash_missing_lastscan ON stash_missing_scenes(last_scan_at);
`

// migratePostgres applies postgresSchemaDDL and then runs the same
// one-time data migrations SQLite's migrate() runs, in the same order.
// Those functions (removeScheduledDownloads, migrateReleaseIdentity,
// backfillReleaseMetadata, cleanupStoredReleaseText,
// backfillLocalAvailableNotifications, normalizeJavLibraryURLs) are plain
// methods on *SQLite, not
// SQLite-specific despite the type name (see that type's doc comment) -
// every query they run is either already portable or was made portable in
// DB Phase 5 (see store.go's cleanupStoredReleaseText and
// removeScheduledDownloads for the two places that needed a small,
// targeted change), so they are reused here unchanged rather than
// duplicated. On a fresh database every one of them affects zero rows and
// exists mainly to leave the same settings completion flags
// (release_identity_dedup_v1, metadata_text_cleanup_v1,
// local_available_notifications_v1) set that a fresh SQLite install would
// have, so the two engines' settings tables never observably disagree
// about what "up to date" means.
func (s *SQLite) migratePostgres(ctx context.Context, report MigrationProgressFunc) error {
	statements := make([]string, 0)
	for _, statement := range strings.Split(postgresSchemaDDL, ";\n") {
		statement = strings.TrimSpace(statement)
		if statement != "" {
			statements = append(statements, statement)
		}
	}
	for current, statement := range statements {
		reportMigration(report, MigrationProgress{Phase: "Database schema", Step: describePostgresMigrationStatement(statement), Current: current + 1, Total: len(statements)})
		if _, err := s.db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	reportMigration(report, MigrationProgress{Phase: "Data compatibility", Step: "Applying existing-installation migrations"})
	// Incremental addition for a PostgreSQL database created before this
	// column existed (TODO-2.0's "Added to StashApp (with date)"). Unlike
	// SQLite, PostgreSQL supports IF NOT EXISTS on ADD COLUMN directly, so
	// this needs no duplicate-column error tolerance.
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE releases ADD COLUMN IF NOT EXISTS stash_added_at TIMESTAMPTZ`); err != nil {
		return err
	}
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE releases ADD COLUMN IF NOT EXISTS stash_release_date TEXT NOT NULL DEFAULT ''`); err != nil {
		return err
	}
	// Incremental addition for a PostgreSQL database created before
	// per-pipeline-step timeouts existed (each step can now override the
	// settings-wide default step timeout individually).
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE pipeline_steps ADD COLUMN IF NOT EXISTS timeout_seconds INTEGER NOT NULL DEFAULT 0`); err != nil {
		return err
	}
	// Incremental addition for a PostgreSQL database created before the
	// Missing Library Files "allow non-preferred filenames" fallback chain
	// and manual Force download override both started recording a
	// structured, filterable flag on the resulting download (TODO-2.0
	// Task A) instead of only free text inside match_reason.
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE downloads ADD COLUMN IF NOT EXISTS filename_pattern_excluded INTEGER NOT NULL DEFAULT 0`); err != nil {
		return err
	}
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE downloads ADD COLUMN IF NOT EXISTS seen_complete BIGINT NOT NULL DEFAULT 0`); err != nil {
		return err
	}
	// Incremental addition for a PostgreSQL database created before the
	// "allow non-preferred filenames" override became a persistent
	// per-release setting instead of a one-off flag on a single Missing
	// Library Files apply run.
	if _, err := s.db.ExecContext(ctx, `ALTER TABLE releases ADD COLUMN IF NOT EXISTS allow_non_preferred_filenames INTEGER NOT NULL DEFAULT 0`); err != nil {
		return err
	}
	// Incremental addition for a PostgreSQL database created before the
	// Release Library Conditions dialog gained the "O Count"/"Last O Count
	// Date"/"Last Played" fields, best-effort-populated from a matched
	// StashApp scene alongside stash_release_date.
	for _, statement := range []string{
		`ALTER TABLE sites ADD COLUMN IF NOT EXISTS watchlist INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE sites ADD COLUMN IF NOT EXISTS auto_monitor_future INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS watchlist INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS o_counter INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS play_count INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS last_played_at TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS last_o_count_at TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS screenshots_checked_at TIMESTAMPTZ`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS watchlist_at TIMESTAMPTZ`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS stash_created_at TIMESTAMPTZ`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS is_preferred INTEGER NOT NULL DEFAULT 1`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS monitor_reason TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS monitor_site_id BIGINT NOT NULL DEFAULT 0`,
		`ALTER TABLE releases ADD COLUMN IF NOT EXISTS ignore_local_force_download INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE job_history ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE job_history ADD COLUMN IF NOT EXISTS scheduled INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE job_history ADD COLUMN IF NOT EXISTS site_count INTEGER NOT NULL DEFAULT 0`,
	} {
		if _, err := s.db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	if err := s.migrateWatchlistNaming(ctx); err != nil {
		return err
	}
	for _, statement := range []string{
		`CREATE INDEX IF NOT EXISTS idx_releases_preferred ON releases(is_preferred,id)`,
		`CREATE INDEX IF NOT EXISTS idx_releases_local_created ON releases(is_local,stash_created_at DESC,id DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_releases_watchlist_date ON releases(watchlist,watchlist_at DESC,id DESC)`,
	} {
		if _, err := s.db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	// Backfill watchlist_at for releases already marked Watchlist before this
	// column existed, so the Release Library's Watchlist-tab "when marked as
	// watchlist" sort has something to sort by right after upgrade instead of
	// every pre-existing Watchlist release tying at NULL. updated_at is the
	// closest available approximation of when watchlist was last toggled true
	// for these rows.
	if _, err := s.db.ExecContext(ctx, `UPDATE releases SET watchlist_at=updated_at WHERE watchlist=1 AND watchlist_at IS NULL`); err != nil {
		return err
	}
	// Backfill stash_created_at the same way the SQLite migration does - see
	// its comment for why stash_added_at is the closest available
	// approximation until the next StashApp sync overwrites it.
	if _, err := s.db.ExecContext(ctx, `UPDATE releases SET stash_created_at=stash_added_at WHERE is_local=1 AND stash_created_at IS NULL AND stash_added_at IS NOT NULL`); err != nil {
		return err
	}
	if err := s.removeScheduledDownloads(); err != nil {
		return err
	}
	if err := s.migrateSiteMonitoringRedesign(ctx); err != nil {
		return err
	}
	if err := s.cleanupStoredReleaseText(ctx); err != nil {
		return err
	}
	if err := s.backfillReleaseMetadata(ctx); err != nil {
		return err
	}
	if err := s.migrateReleaseIdentity(ctx); err != nil {
		return err
	}
	if err := s.migrateNormalizedReleaseMetadata(ctx); err != nil {
		return err
	}
	if _, err := s.db.ExecContext(ctx, `UPDATE sites SET download_mode='future' WHERE download=1 AND download_mode=''`); err != nil {
		return err
	}
	if err := s.backfillLocalAvailableNotifications(ctx); err != nil {
		return err
	}
	if err := s.normalizeJavLibraryURLs(); err != nil {
		return err
	}
	return s.normalizeReleaseTimestamps(ctx)
}

// OpenPostgresStore opens a fully migrated PostgreSQL-backed Store: it
// opens a connection pool via OpenPostgres (DB Phase 3's driver/pool
// setup, including the DB Phase 5 query-rewriting connector - see
// postgres_rewrite.go), applies postgresSchemaDDL and the one-time data
// migrations via migratePostgres, and returns the same *SQLite type
// OpenSQLite returns (see that type's doc comment for why that is not a
// naming mistake). If migration fails, the pool is closed before
// returning so a caller cannot end up holding a half-migrated connection.
func OpenPostgresStore(ctx context.Context, c PostgresConfig) (*SQLite, error) {
	return OpenPostgresStoreWithProgress(ctx, c, nil)
}

// OpenPostgresStoreWithProgress is OpenPostgresStore with a read-only progress
// callback for startup and recovery UIs. The callback is never allowed to
// affect migration behavior and receives no credentials or row data.
func OpenPostgresStoreWithProgress(
	ctx context.Context,
	c PostgresConfig,
	report MigrationProgressFunc,
) (*SQLite, error) {
	reportMigration(report, MigrationProgress{
		Phase: "Database connection",
		Step:  "Connecting to PostgreSQL",
	})

	// Only the connection/ping phase gets a short timeout.
	// Migrations and backfills may legitimately take much longer.
	connectCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	db, err := OpenPostgres(connectCtx, c)
	cancel()

	if err != nil {
		return nil, err
	}

	s := &SQLite{
		db:      db,
		dialect: PostgresDialect{},
	}

	// Use the original context for migrations, not connectCtx.
	if err := s.migratePostgres(ctx, report); err != nil {
		db.Close()
		return nil, err
	}

	reportMigration(report, MigrationProgress{
		Phase: "Release preferences",
		Step:  "Updating saved ignore-tag and title filters",
	})

	// This may perform the large releases UPDATE and must not inherit
	// the 30-second connection deadline.
	if err := s.initializeReleasePreferences(ctx); err != nil {
		db.Close()
		return nil, err
	}

	reportMigration(report, MigrationProgress{
		Phase:   "Database ready",
		Step:    "Database migrations completed",
		Current: 1,
		Total:   1,
	})

	return s, nil
}
